name: peribolos

on:
  workflow_call:
    inputs:
        confirm:
            required: false
            type: boolean
        dump:
            required: false
            type: string

env:
    API_TOKEN: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
    ADMIN_LIST: "detiber,justaugustus,lelia,openclarity-service,svrnm"
    ADMIN_COUNT: 5

jobs:
  peribolos:
    name: run-peribolos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 🔒 harden runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit
      - name: 🔑 set token
        run: echo "${{ env.API_TOKEN }}" > token
      - name: 🚮 dump config
        if: inputs.dump != ''
        uses: docker://ghcr.io/uwu-tools/peribolos:v0.0.4
        with:
          github-token-path: ./token
          dump: ${{ inputs.dump }}
      - name: 🔄 run peribolos
        if: inputs.confirm == true || false
        uses: docker://ghcr.io/uwu-tools/peribolos:v0.0.4
        with:
          github-token-path: ./token
          config-path: org
          required-admins: ${{ env.ADMIN_LIST }}
          min-admins: ${{ env.ADMIN_COUNT }}
          require-self: true
          fix-org: true
          fix-org-members: true
          fix-teams: true
          fix-team-members: true
          confirm: ${{ inputs.confirm || false }}
