name: _repo

on:
  workflow_call:
    inputs:
      org1:
        type: string
        required: false
        default: "cisco-open"
      org2:
        type: string
        required: false
        default: "openclarity"
      org3:
        type: string
        required: false
        default: "banzaicloud"
      org4:
        type: string
        required: false
        default: "CiscoDevNet"
      org5:
        type: string
        required: false
        default: "cisco-ospo"
      exempt:
        type: string
        required: false
        default: "keep,template"
      inactive:
        type: number
        required: false
        default: 365
      assignee:
        type: string
        required: false
        default: "lelia"

jobs:
  repo:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        org:
          [
            "${{ inputs.org1 }}",
            "${{ inputs.org2 }}",
            "${{ inputs.org3 }}",
            "${{ inputs.org4 }}",
            "${{ inputs.org5 }}",
          ]
    steps:
      - name: 🔍 find stale repos
        uses: github/stale-repos@v1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORGANIZATION: ${{ matrix.org }}
          EXEMPT_TOPICS: ${{ inputs.exempt }}
          INACTIVE_DAYS: ${{ inputs.inactive }}
      - name: 📝 create repo report
        uses: peter-evans/create-issue-from-file@v4
        with:
            title: "📝 Stale Repository Report: ${{ matrix.org }}"
            content-filepath: "./stale_repos.md"
            assignees: ${{ inputs.assignee }}
            token: ${{ secrets.GITHUB_TOKEN }}
