name: _scorecard

on:
  workflow_call:
    inputs:
      publish-results:
        description: Publish results of Scorecard analysis
        type: boolean
        required: false
        default: true

# Restrict top-level permissions
permissions:
  id-token: none
  security-events: none

jobs:
  scorecard:
    runs-on: ubuntu-latest
    permissions:
        # Required for GitHub OIDC token (if publish_results: true)
        id-token: write
        # Required for code scanning (GitHub CodeQL) alerts
        security-events: write
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          persist-credentials: false
      - name: ✅ run scorecard analysis
        uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736 # v2.3.1
        with:
          results_file: results.sarif
          results_format: sarif
          # Publish the results for public repositories to enable Scorecard badges: 
          # https://github.com/ossf/scorecard-action#publishing-results
          publish_results: ${{ inputs.publish-results }}
          # (Optional) fine-grained personal access token (PAT)
          repo_token: ${{ secrets.SCORECARD_TOKEN }}
      # (Optional) Upload the results as SARIF artifacts
      - name: ⏫ upload sarif artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4.3.1
        with:
          name: SARIF file
          path: results.sarif
          retention-days: 5
      # Required for code scanning (CodeQL) alerts
      - name: 📦 upload sarif results
        uses: github/codeql-action/upload-sarif@e8893c57a1f3a2b659b6b55564fdfdbbd2982911 # v3.24.0
        with:
          sarif_file: results.sarif
