name: _sync

on:
  workflow_call:
    inputs:
      force:
        type: boolean
        required: false
        default: false

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 🔄 sync branch
        uses: connor-baer/action-sync-branch@v1.0.3
        with:
          branch: main
          token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
          force: ${{ inputs.force }}
