name: app-test

on: [workflow_dispatch]

permissions:
    issues: none
    pull-requests: none

jobs:
  hello-world:
    runs-on: ubuntu-latest
    permissions:
        issues: write
        pull-requests: write
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}
      - uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ steps.app-token.outputs.token }}
          issue-number: 117
          body: "Hello, World!"
