name: evergreen-check

on:
  # Scheduled trigger
  schedule:
    # Run weekly on Saturdays
    - cron: "30 1 * * 6"
  # Manual trigger
  workflow_dispatch:

permissions:
  issues: none

jobs:
  clean-owners:
    runs-on: ubuntu-latest
    steps:
      - name: 🧼 clean codeowners
        uses: github/cleanowners@6e9f77116c2528ea49f31bb3b830bc2a31129f8a # no semver release yet
        env:
          GH_TOKEN: ${{ secrets.CISCO_SERVICE_TOKEN }}
          ORGANIZATION: cisco-ospo
          EXEMPT_REPOS: "cisco-ospo/.github, cisco-ospo/.allstar"
          DRY_RUN: true
