name: clean-owners

on:
  # Scheduled trigger
  schedule:
    # Run weekly on Saturdays
    - cron: "30 1 * * 6"
  # Manual trigger
  workflow_dispatch:

permissions:
  issues: none

jobs:
  clean-owners:
    runs-on: ubuntu-latest
    permissions:
        issues: write
    steps:
      - name: 🧼 clean codeowners
        uses: github/cleanowners@211ccef1800cfd62cd8cacec1e7fafe890bb0b50 # no semver release yet
        env:
          GH_TOKEN: ${{ secrets.CISCO_SERVICE_TOKEN }}
          ORGANIZATION: cisco-ospo
          EXEMPT_REPOS: "cisco-ospo/.github, cisco-ospo/.allstar"
          DRY_RUN: true
