name: dry-run

on:
  push:
    branches: [develop]
    paths:
      - org/**
  workflow_dispatch:

jobs:
  lint-yaml:
    uses: ./.github/workflows/_lint.yml
  dry-run:
    uses: ./.github/workflows/_sync.yml
    permissions: read-all
    secrets: inherit
    with:
      confirm: false
