name: dry-run

on:
  push:
    branches: [develop]
    paths:
      - org/**
  workflow_dispatch:
    inputs:
        force-sync:
            type: boolean
            required: false

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
  peribolos:
    needs: lint
    uses: ./.github/workflows/_peribolos.yml
    permissions: read-all
    secrets: inherit
    with:
      confirm: false
  sync:
    needs: peribolos
    uses: ./.github/workflows/_sync.yml
    secrets: inherit
    with:
      force: false
