name: prod-run

on:
  push:
    branches: [main]
    paths:
      - org/**
  schedule:
    - cron:  '0 * * * *'
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
  run:
    needs: lint
    uses: ./.github/workflows/_peribolos.yml
    permissions: read-all
    secrets: inherit
    with:
      confirm: true
