name: run-scorecard

on:
  push:
    branches:
      # Run on pushes to default branch
      - develop
  schedule:
    # Run weekly on Saturdays
    - cron: "30 1 * * 6"
  # Only the default branch is supported
  branch_protection_rule:
  # Run the workflow manually
  workflow_dispatch:

jobs:
  run-scorecard:
    # Call reusable workflow file
    uses: ./.github/workflows/_scorecard.yml
    permissions: read-all
    secrets: inherit
    with:
      # Publish results of Scorecard analysis
      publish-results: true
