name: sync-branch

on:
  push:
    branches: [develop]
    paths:
      - org/**
  workflow_dispatch:

jobs:
  sync:
    name: sync-develop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: 🔄 sync branch
      uses: connor-baer/action-sync-branch@v1.0.3
      with:
        branch: main
        token: ${{ secrets.SERVICE_ACCOUNT_TOKEN }}
        force: false
